spring:
  application:
    name: quotation-app

  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/bitmoi
    username: root
    password: password
#    pool:
#      initial-size: 5
#      max-size: 20
#      max-idle-time: 30m
#      validation-query: SELECT 1

  kafka:
    producer:
      bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080